- name: Get Incident Details
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars:
    snow_instance: "nowlearning-nlinst04302549-63gqx-0001"
    snow_user: "admin"
    snow_password: "9TnFc8CuNApy"
    target_assignment_group: "Database Support"
 
  tasks:
 
    - name: Get incident details
      uri:
        url: "https://{{ snow_instance }}.lab.service-now.com/api/now/table/incident?sysparm_query=number={{ incident_number }}"
        method: GET
        user: "{{ snow_user }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
      register: incident
 
    - name: Save incident values
      set_fact:
        sys_id: "{{ incident.json.result[0].sys_id }}"
        short_description: "{{ incident.json.result[0].short_description }}"
 
    - name: Extract IP address
      set_fact:
        target_ip: "{{ short_description | regex_search('([0-9]{1,3}(?:\\.[0-9]{1,3}){3})') }}"
 
    - name: Display IP
      debug:
        msg: "Target IP = {{ target_ip }}"
 
    - name: Add target host dynamically
      add_host:
        name: "{{ target_ip }}"
        groups: mariadb_targets
 
 
- name: Restart MariaDB
  hosts: ubuntu
  become: true
  gather_facts: false
 
  tasks:
 
    - name: Restart mariadb
      service:
        name: mariadb
        state: restarted
 
    - name: Verify mariadb
      shell: systemctl is-active mariadb
      register: mariadb_status
      retries: 5
      delay: 10
      until: mariadb_status.stdout == "active"
      ignore_errors: true
 
    - name: Store status
      set_stats:
        data:
          mariadb_running: "{{ mariadb_status.stdout | trim == 'active' }}"
  
- name: Update Incident
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars:
    snow_instance: "nowlearning-nlinst04302549-63gqx-0001"
    snow_user: "admin"
    snow_password: "9TnFc8CuNApy"
    target_assignment_group: "Database Support"
 
  tasks:
 
    - name: Resolve incident
      uri:
        url: "https://{{ snow_instance }}.lab.service-now.com/api/now/table/incident/{{ hostvars['localhost']['sys_id'] }}"
        method: PATCH
        user: "{{ snow_user }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body:
          incident_state: "6"
          close_code: "Solved (Permanently)"
          close_notes: "MariaDB restarted successfully by AAP."
          work_notes: |
            Automation Action:
            - Restarted MariaDB
            - Service verified ACTIVE
            - Incident auto resolved
      when: mariadb_running | default(false)
 
    - name: Reassign incident
      uri:
        url: "https://{{ snow_instance }}.lab.service-now.com/api/now/table/incident/{{ hostvars['localhost']['sys_id'] }}"
        method: PATCH
        user: "{{ snow_user }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body:
          assignment_group: "{{ target_assignment_group }}"
          work_notes: |
            Automation Action:
            - Restart attempted
            - MariaDB still not running
            - Routed to Database Support Team
      when: not mariadb_running | default(false)
 
