---
- name: Get Incident Details
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars:
    snow_instance: "nowlearning-nlinst04302549-63gqx-0001"
    snow_user: "admin"
    snow_password: "9TnFc8CuNApy"
    target_assignment_group: "Database Support"
 
  tasks:
 
    - name: Get incident details
      uri:
        url: "https://{{ snow_instance }}.lab.service-now.com/api/now/table/incident?sysparm_query=number={{ incident_number }}"
        method: GET
        user: "{{ snow_user }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
      register: incident
 
    - name: Save values
      set_fact:
        sys_id: "{{ incident.json.result[0].sys_id }}"
        description: "{{ incident.json.result[0].description }}"
 
    - name: Extract IP address
      set_fact:
        target_ip: "{{ description | regex_search('([0-9]{1,3}(?:\\.[0-9]{1,3}){3})') }}"
 
    - debug:
        msg: "Target IP = {{ target_ip }}"
 
    - name: Add host dynamically
      add_host:
        name: "{{ target_ip }}"
        groups: mariadb_targets
 
##########################################################
 
- name: Restart MariaDB
  hosts: mariadb_targets
  become: false
  gather_facts: false
 
  tasks:
 
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
 
    - name: Verify service
      shell: systemctl is-active mariadb
      register: mariadb_status
      retries: 5
      delay: 10
      until: mariadb_status.stdout | trim == "active"
 
    - name: Save status to localhost
      delegate_to: localhost
      delegate_facts: true
      set_fact:
        mariadb_running: "{{ mariadb_status.stdout | trim == 'active' }}"
 
##########################################################
 
- name: Update ServiceNow
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars:
    snow_instance: "nowlearning-nlinst04302549-63gqx-0001"
    snow_user: "admin"
    snow_password: "9TnFc8CuNApy"
    target_assignment_group: "Database Support"
 
  tasks:
 
    - debug:
        var: mariadb_running
 
    - name: Resolve incident
      uri:
        url: "https://{{ snow_instance }}.lab.service-now.com/api/now/table/incident/{{ sys_id }}"
        method: PATCH
        user: "{{ snow_user }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body:
          incident_state: "6"
          close_code: "Solved (Permanently)"
          close_notes: "MariaDB restarted successfully by AAP."
          work_notes: |
            Automation Action:
            - Restarted MariaDB
            - Verified ACTIVE
            - Incident auto resolved
      when: mariadb_running | bool
 
    - name: Reassign incident
      uri:
        url: "https://{{ snow_instance }}.lab.service-now.com/api/now/table/incident/{{ sys_id }}"
        method: PATCH
        user: "{{ snow_user }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body:
          assignment_group: "{{ target_assignment_group }}"
          work_notes: |
            Automation Action:
            - Restart attempted
            - MariaDB still not running
            - Routed to Database Support Team
      when: not mariadb_running | bool
